//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Manifest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Manifest() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.Resources.Manifest", typeof(Manifest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -10
        ///+6
        ///-1
        ///-18
        ///-19
        ///+8
        ///-18
        ///-9
        ///-9
        ///+8
        ///+13
        ///+6
        ///-11
        ///+19
        ///-15
        ///-9
        ///-1
        ///+5
        ///+14
        ///-7
        ///+18
        ///-10
        ///+16
        ///+18
        ///+9
        ///-1
        ///+16
        ///-12
        ///-7
        ///-20
        ///+14
        ///-18
        ///+16
        ///-2
        ///-6
        ///-22
        ///+3
        ///+3
        ///-20
        ///+16
        ///+8
        ///-15
        ///-12
        ///-12
        ///-6
        ///-16
        ///-18
        ///-15
        ///-1
        ///+9
        ///+11
        ///+12
        ///-17
        ///-3
        ///+12
        ///+16
        ///+9
        ///+11
        ///+19
        ///+18
        ///+9
        ///+19
        ///-13
        ///+10
        ///+12
        ///+17
        ///-14
        ///-2
        ///+10
        ///-2
        ///+12
        ///+18
        ///-7
        ///+2
        ///+12
        ///-8
        ///-19
        ///+16
        ///+14
        ///+8
        ///-3
        ///+14
        ///+17
        ///-8
        ///-17
        ///+18
        ///-7
        ///-18
        ///-16
        ///+7
        ///+14
        ///-3
        ///-13
        ///+20
        ///+13
        ///+15
        ///+19
        ///+11
        ///+13
        ///-19
        ///+5
        ///+11
        ///+7
        ///+9
        ///+3
        ///+14
        ///-1
        ///+6
        ///-15
        ///-8
        ///-2
        ///+ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dghfbsyiznoumojleevappwqtr
        ///dghfbsyiznoumkjljevacpmqer
        ///dghfbbyizioumkjlxevacpwdtr
        ///dghfbsesznoumkjlxevacpwqkr
        ///dghfbsynznoumkjlxziacpwqtr
        ///cghfbsyiznjumkjlxevacprqtr
        ///dghfjsyizwoumkjlxevactwqtr
        ///dghfdsyfinoumkjlxevacpwqtr
        ///hghfbsyiznoumkjlxivacpwqtj
        ///dgcfbsyiznoumkjlxevacbuqtr
        ///dghfbsyiznoymnjlxevacpwvtr
        ///dfhfbsyiznoumkulxevacptqtr
        ///dghfasyiznovmkjlxevacpwqnr
        ///dghfbsyihnouikjlxevackwqtr
        ///dghfbayiznolmkjlyevacpwqtr
        ///jghfbsyiznoumnjldevacpwqtr
        ///dhhfbsyuznoumkjlxevakpwqtr
        ///nehfrsyiznoumkjlxevacpwqtr
        ///dghfbsyi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2 {
            get {
                return ResourceManager.GetString("Day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1 @ 604,100: 17x27
        ///#2 @ 861,26: 23x24
        ///#3 @ 875,844: 29x20
        ///#4 @ 524,114: 24x24
        ///#5 @ 696,820: 26x19
        ///#6 @ 746,795: 19x14
        ///#7 @ 48,965: 24x29
        ///#8 @ 798,18: 27x18
        ///#9 @ 296,182: 17x13
        ///#10 @ 189,299: 27x16
        ///#11 @ 416,282: 13x16
        ///#12 @ 428,975: 13x15
        ///#13 @ 16,803: 20x25
        ///#14 @ 432,825: 12x18
        ///#15 @ 974,894: 22x12
        ///#16 @ 312,37: 27x12
        ///#17 @ 117,474: 17x24
        ///#18 @ 319,163: 25x18
        ///#19 @ 593,759: 15x21
        ///#20 @ 725,551: 22x18
        ///#21 @ 278,959: 18x20
        ///#22 @ 178,871: 24x29
        ///#23 @ 143,688: 25x24
        ///#24 @ 803,5: 17x16
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day3 {
            get {
                return ResourceManager.GetString("Day3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1518-05-28 00:59] wakes up
        ///[1518-06-29 00:54] falls asleep
        ///[1518-08-22 00:16] falls asleep
        ///[1518-07-04 00:46] wakes up
        ///[1518-09-02 00:00] Guard #2137 begins shift
        ///[1518-05-01 00:45] falls asleep
        ///[1518-08-15 00:47] wakes up
        ///[1518-07-03 00:56] wakes up
        ///[1518-11-17 00:02] Guard #563 begins shift
        ///[1518-11-08 00:46] falls asleep
        ///[1518-09-14 00:37] wakes up
        ///[1518-03-06 00:49] wakes up
        ///[1518-03-21 00:37] falls asleep
        ///[1518-07-11 00:03] Guard #2083 begins shift
        ///[1518-02-18 00:34] wakes up
        ///[1518-06-0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day4 {
            get {
                return ResourceManager.GetString("Day4", resourceCulture);
            }
        }
    }
}
